imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    trusted_hosts:   ~
    session:
        handler_id: ~
        cookie_httponly: true
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    rpe.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'rss', [@rpe.view_handler.rss, 'createResponse'] ] ]
            - ['registerHandler', [ 'ics', [@rpe.view_handler.ics, 'createResponse'] ] ]

    rpe.view_handler.rss:
        class: Rpe\RestBundle\Extension\RestViewHandler\RssViewHandler

    rpe.view_handler.ics:
        class: Rpe\RestBundle\Extension\RestViewHandler\IcsViewHandler

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    bundles:        [ PumWoodworkBundle, PumProjectAdminBundle, PumAppBundle, RpePumBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    _pum:
                        mapping:   true
                        type:      yml
                        dir:       %kernel.root_dir%/../vendor/pum/pum/src/Pum/Core/Resources/config/doctrine
                        prefix:    Pum\Core\Definition
                        alias:     Pum
                        is_bundle: false
                    PumAppBundle:      ~
                    PumWoodworkBundle: ~
                    PumProjectAdminBundle: ~

# Swiftmailer Configuration
swiftmailer:
    default_mailer: first_mailer
    mailers:
        first_mailer:
            transport: %mailer_transport%
            host:      %mailer_host%
        second_mailer:
            transport: %mailer_transport%
            host:      %mailer_host%
            logging: false

# HTML Purifier Configuration
exercise_html_purifier:
    default:
        Cache.SerializerPath: '%kernel.cache_dir%/htmlpurifier'

#Mobile detect
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~

pum_core:
    validation: true
    em_factory: true
    view:
        enabled: true
    assetic_bundles: [ RpePumBundle ]

pum_type_extra:
    media:
        enabled: true
        storage:
            filesystem:
                date_folder: true
                directory  : %kernel.root_dir%/../web
                path:        /medias/default/

fos_rest:
    format_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        failed_validation: HTTP_BAD_REQUEST
        default_engine: php
        formats:
            json: true
            rss: true
            ics: true
    format_listener:
        prefer_extension: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    routing_loader:
        default_format: json
    service:
        router: router
        templating: templating
        serializer: serializer
        view_handler: rpe.view_handler